version: '3.7'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack_service
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data

    volumes:
      - ./tmp/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
