AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: ./
      Environment:
        Variables:
          AWS_ENDPOINT: "http://192.168.56.101:4566"
          AWS_S3_BUCKET_NAME: "aaa"
